CREATE TABLE Funcao(
   Cod_Funcao       VARCHAR(22) NOT NULL PRIMARY KEY
  ,Descrição_Função VARCHAR(33)
);
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('-1','Não Informado');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('Al.CFOAer','Alunos CFOAeronáutica');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('Aspirante','Aspirantes');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CA-I','Cargo Comissionado de Assessoria');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CA-II','Cargo Comissionado de Assessoria');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CA-III','Cargo Comissionado de Assessoria');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('Cargos Nat','Cargos Natureza Especial');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CAS-I','Cargo Comissionado de Assistência');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CAS-II','Cargo Comissionado de Assistência');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CCD-I','Cargo Comissionado de Direção');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CCD-II','Cargo Comissionado de Direção');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CCT-I','Cargo Comissionado Técnico');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CCT-II','Cargo Comissionado Técnico');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CCT-III','Cargo Comissionado Técnico');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CCT-IV','Cargo Comissionado Técnico');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CCT-V','Cargo Comissionado Técnico');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CCX-0110','CCX-0110');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CCX-0113','CCX-0113');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CCX-0115','CCX-0115');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CCX-0117','CCX-0117');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CCX-0118','CCX-0118');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CCX-0207','CCX-0207');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CCX-0210','CCX-0210');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CCX-0213','CCX-0213');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CCX-0215','CCX-0215');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CCX-0313','CCX-0313');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CD-0001','Cargo Comissionado de Direção');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CD-0002','Cargo Comissionado de Direção');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CD-0003','Cargo Comissionado de Direção');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CD-0004','Cargo Comissionado de Direção');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CGE-0001','Cargo de Gerência Executiva');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CGE-0002','Cargo de Gerência Executiva');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CGE-0003','Cargo de Gerência Executiva');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CGE-0004','Cargo de Gerência Executiva');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('CNE-0001','Cargo de Natureza Especial');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('Comandante Aeronáutica','Comandante da Aeronáutica');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('Comandante Exército','Comandante do Exército');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('Comandante Marinha','Comandante da Marinha');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('DAS-1011','Cargo de Assessoramento');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('DAS-1012','Cargo de Assessoramento');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('DAS-1013','Cargo de Coordenação');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('DAS-1014','Cargo de Coordenação');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('DAS-1015','Cargo de Direção');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('DAS-1016','Cargo Superior');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('DAS-1021','Cargo de Assessoramento');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('DAS-1022','Cargo de Assessoramento');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('DAS-1023','Cargo de Coordenação');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('DAS-1024','Cargo de Coordenação');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('DAS-1025','Cargo de Direção');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('DAS-1026','Cargo de Direção');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('DAS-1033',NULL);
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('DAS-1034','DAS-1034');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('DAS-1035','Cargo de Direção');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FCT-01','Função Comissionada Técnica');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FCT-02','Função Comissionada Técnica');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FCT-03','Função Comissionada Técnica');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FCT-04','Função Comissionada Técnica');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FCT-05','Função Comissionada Técnica');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FCT-07','Função Comissionada Técnica');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FCT-08','Função Comissionada Técnica');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FCT-09','Função Técnica Comissionada');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FCT-10','Função Técnica Comissionada');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FCT-11','Função Técnica Comissionada');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FCT-12','Função Técnica Comissionada');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FCT-13','Função Técnica Comissionada');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FCT-14','Função Técnica Comissionada');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FCT-15','Função Técnica Comissionada');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FEX-0211','FEX-0211');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FG-0001','FG-0001');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FG-0002','FG-0002');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FG-0003','FG-0003');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FG-0004','FG-0004');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FG-0005','FG-0005');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FGR-1','FGR-1');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FGR-2','FGR-2');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FGR-3','FGR-3');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FPE-1011','FPE-1011');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FPE-1012','FPE-1012');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FPE-1013','FPE-1013');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FPE-1014','FPE-1014');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FPE-1015','FPE-1015');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FPE-1021','FPE-1021');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FPE-1022','FPE-1022');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FPE-1023','FPE-1023');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FPE-1024','FPE-1024');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FPE-1031','FPE-1031');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FPE-1034','FPE-1034');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FPE-1035','FPE-1035');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FPE-1042','FPE-1042');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FPE-1043','FPE-1043');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('FUC-0001','FUC-0001');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('GR-02',NULL);
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('GSE-0001','GSE-0001');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('GSE-0003','GSE-0003');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('GSE-0004','GSE-0004');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('GSE-0005','GSE-0005');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('GSE-0006','GSE-0006');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('GSE-0007','GSE-0007');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('GTS-002','Gratificação Temporária - SIPAM');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('NES-0007','Cargo de Natureza Especial');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('NES-0008','Cargos de Natureza Especial');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('NES-0017','Cargo de Natureza Especial');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('NES-0029','Cargos de Natureza Especial');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('NES-0052','Cargo de natureza Especial');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('NES-0080','Cargo de Natureza Especial');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('NES-0081','Cargo de Natureza Especial');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('NES-0086','NES-0086');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('NES-0089','NES-0089');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('Of.General','Oficiais Generais');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('OfIntermed','OfIntermed');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('OfSubalter','OfSubalter');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('OfSuperior','OfSuperior');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('Praça Esp','Praças Especiais');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('Praças','Praças');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('RGA-0002','RGA-0002');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('RGA-0003','RGA-0003');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('RGA-0004','RGA-0004');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('RGA-0005','RGA-0005');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('RMA-0002','RMA-0002');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('RMA-0004','RMA-0004');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('RMA-0005','RMA-0005');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('RMP-0001','Nível I - RMP01');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('RMP-0002','Nível II - RMP02');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('RMP-0004','Nível IV - RMP04');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('Sargento','Sargentos');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('Sigilosa','Informações protegidas por sigilo');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('Suboficial','Suboficial');
INSERT INTO Funcao(Cod_Funcao,Descrição_Função) VALUES ('Subtenente','Subtenentes');
